# This is a basic workflow to help you get started with Actions

name: owasp scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # f This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build
        run: |
          yarn build

      - name: Start
        run: |
          yarn start &
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://localhost:3000/'
          cmd_options: '-d'
